### ISSUE TITLE
Multisig. Can't get an invitation for EVM Multisig

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1576]
## Description
If invite someone to EVM multisig account who has version 1.5.0 or bellof it drops an error and do nothing:

```
2024/03/14 17:10:06.983 [stage#1.6.0-3]-renderer [info]  > 💛 ===> Matrix: Multisig invite {
  eventId: '$NIlDXpmqCOHcimK6gi-FY9Xi9Jvxh3v8p8zngConBIM',
  roomId: '!SLLYyJhUdmHvGrTIlC:matrix.org',
  sender: '@mister_coin:matrix.org',
  client: '@solocrack:matrix.org',
  date: '2024-03-14T14:10:02.314Z',
  type: 'm.room.member',
  content: {
    mstAccount: {
      accountId: '0x33cb757ae12209f89f85da32b29522726e9b1568',
      accountName: 'test',
      creatorAccountId: '0x4c2ab98b646ce36df6a4a4407ab9fcee1c90549a',
      signatories: '[Array]',
      threshold: 2
    }
  },
  roomName: 'Nova Spektr MST | test'
}
2024/03/14 17:10:06.984 [stage#1.6.0-3]-renderer [error] > Error processing Multisig invitation @mister_coin:matrix.org Nova Spektr MST | test !SLLYyJhUdmHvGrTIlC:matrix.org $NIlDXpmqCOHcimK6gi-FY9Xi9Jvxh3v8p8zngConBIM Error: Multisig address 0x33cb757ae12209f89f85da32b29522726e9b1568 can't be derived from signatories and threshold
    at validateMstAccount (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:6502)
    at Object.<anonymous> (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:5182)
    at step (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:3017)
    at Object.next (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:2277)
    at MatrixContext_asyncGeneratorStep (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:105)
    at _next (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:430)
    at file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:608
    at new Promise (<anonymous>)
    at Object.<anonymous> (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:343)
    at Object.onInvite (file:///Applications/Nova%20Spektr%20Stage.app/Contents/Resources/app.asar/renderer-d8ba94dfee551b68362b.js:454826:6297)
```

**Case:**
1. Use 2 apps
2. In first app - Create Single Chain Multisig EVM wallet (in Moonbeam e.g.)
3. In second app receive and invitation via matrix

**Actual result:**
Multisig in second app won't be created, error while parsing

**Expected result:**
Create EVM multisig on second app

**Comment by stepanLav** [comment]
Status verification: ✅
