### ISSUE TITLE
Undefined crash, when use pure proxy in Multisig

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1656]
## Description

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/c957cbf9-d356-48a3-9db5-1a0e9e6dc215

</details>

## Steps to Reproduce

1. Create multisig with pure proxy
2. Create operation set reward destination
3. Open operation details

## Actual Behavior

```
2024/04/09 13:57:07.023 [stage#1.5.0]-renderer [error] > Error: Objects are not valid as a React child (found: object with keys {account}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (renderer-dfd28ad82f6f8ae86e3e.js:22424:9)
    at reconcileChildFibers (renderer-dfd28ad82f6f8ae86e3e.js:23365:7)
    at reconcileChildren (renderer-dfd28ad82f6f8ae86e3e.js:26699:28)
    at updateHostComponent (renderer-dfd28ad82f6f8ae86e3e.js:27456:3)
    at beginWork (renderer-dfd28ad82f6f8ae86e3e.js:29150:14)
    at beginWork$1 (renderer-dfd28ad82f6f8ae86e3e.js:34958:14)
```

## Environment
https://github.com/novasamatech/nova-spektr/commit/ca555571245870d28cad4cd0c3ea42cb09c3d98d

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
Reproduced, got undefined in [toShortAddress](https://github.com/novasamatech/nova-spektr/blob/c4e95f0a7be98969520c96edd915917e273c63de/src/renderer/shared/lib/utils/address.ts#L43-L45)

test address: 5F563AYeZ7cV6jAt1voUzoNrjs7MHpWgVyuydJYumoZEjoFi

<img width="1464" alt="Screenshot 2024-04-10 at 12 56 17" src="https://github.com/novasamatech/nova-spektr/assets/40560660/03f02b23-bf7b-410b-b629-a27c6b59a74e">

**Comment by stepanLav** [comment]
Status verification: ✅
