### ISSUE TITLE
Issue with Linux auto update

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1735]
Nova Spektr download path is wrong for Linux build (reported via [Polkassembly](https://polkadot.polkassembly.io/referenda/676#662c3d178d4af107ea964372))

```
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
2024/04/27 01:40:33.581 [production#1.7.0]-main [error] > Error: Error: Cannot download "https://github.com/novasamatech/nova-spektr/releases/download/v1.7.1/Nova-Spektr-1.7.1.AppImage", status 404: 
    at ClientRequest.<anonymous> (/tmp/.mount_Nova-SI1i5Rt/resources/app.asar/main.js:8:45960)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109319)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
2024/04/27 01:40:33.582 [production#1.7.0]-main [error] > [app-updater] Error on update Error: Cannot download "https://github.com/novasamatech/nova-spektr/releases/download/v1.7.1/Nova-Spektr-1.7.1.AppImage", status 404: 
    at ClientRequest.<anonymous> (/tmp/.mount_Nova-SI1i5Rt/resources/app.asar/main.js:8:45960)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109319)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
^C^C
```

Short term fix: change `latest-linux.yml` or artifact file name
Long term fix: change CI

**Comment by stepanLav** [comment]
Status verification: ✅
