### ISSUE TITLE
Mythos. Create multisig. Unable to create Enum via index 148, in Ed25519, Sr25519, Ecdsa

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2843]
## Description

Can't create multisig

![Screenshot 2024-12-11 at 19 40 16](https://github.com/user-attachments/assets/8c099c92-6b70-4c82-8537-2cc425389068)

Error:

```
Uncaught (in promise) Error: createType(ExtrinsicSignature):: Unable to create Enum via index 148, in Ed25519, Sr25519, Ecdsa
    at createTypeUnsafe (type.js:51:1)
    at TypeRegistry.createTypeUnsafe (registry.js:226:32)
    at Type.addSignature (ExtrinsicSignature.js:123:1)
    at Type.addSignature (Extrinsic.js:64:1)
    at Submittable.addSignature (Extrinsic.js:273:1)
    at Object.signAndSubmit (transactionService.ts:90:13)
    at push../src/renderer/features/operations/OperationSubmit/model/submit-model.ts.signAndSubmitExtrinsicsFx.sid (submit-model.ts:87:26)
    at Nt (effector.mjs:1:26246)
    at effector.mjs:1:8166
    at o (effector.mjs:1:2031)
```

## Steps to Reproduce

1. Go to Multisig creation flow
2. Select Mythos
3. Fill required data
4. Create

## Expected Behavior
Submit system.remark()

## Actual Behavior
Stuck on submission

## Environment
https://github.com/novasamatech/nova-spektr/commit/ce34409a7ea0b791c4782b2b6a8858fa48620942

**Comment by pgolovkin** [comment]
Type definition https://github.com/polkadot-js/apps/blob/488fa2417f2d0a8728823db7c8492855d9ca2322/packages/apps-config/src/api/spec/mythos.ts

**Comment by stepanLav** [comment]
Status verification: ✅
